version: "3.7"

volumes:
  elasticsearch_data: {}

services:
  jaegerdemoclient:
    container_name: jaegerdemoclient
    environment:
      - "JAEGER_AGENTHOST=jaeger-agent"
      - "JAEGER_AGENTPORT=6831"
      - "DEMOCLIENT_LOOPCOUNT=500"
    image: jaegerdemoclient
    build: .

  elasticsearch:
    container_name: elasticsearch
    environment:
      - "discovery.type=single-node"
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.3
    restart: unless-stopped
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - "elasticsearch_data:/usr/share/elasticsearch/data"

  jaeger-agent:
    container_name: jaeger-agent
    command: 
      - "--reporter.grpc.host-port=jaeger-collector:14250"
      # - "--log-level=debug"
    depends_on:
      - jaeger-collector
    image: jaegertracing/jaeger-agent
    ports:
    # - "5775:5775/udp" # deprecated
      - "6831:6831/udp" # compact Thrift protocol used by most current Jaeger clients
    # - "6832:6832/udp" # binary Thrift protocol used by Node.js Jaeger client
      - "5778:5778"     # serve configs, sampling strategies
      - "14271:14271"   # admin port: health check at / and metrics at /metrics
    restart: unless-stopped

  jaeger-collector:
    # command: 
    #   - "--log-level=debug"
    container_name: jaeger-collector
    depends_on:
      - elasticsearch
    environment:
      - "SPAN_STORAGE_TYPE=elasticsearch"
      - "ES_SERVER_URLS=http://elasticsearch:9200"
    image: jaegertracing/jaeger-collector
    ports:
      - "14269:14269" # admin port: health check at / and metrics at /metrics
      - "14268:14268" # can accept spans directly from clients in jaeger.thrift format over binary thrift protocol
      - "14250:14250" # used by jaeger-agent to send spans in model.proto format
    # - "9411:9411"   # can accept Zipkin spans in Thrift, JSON and Proto (disabled by default)
    restart: unless-stopped

  jaeger-query:
    container_name: jaeger-query
    depends_on:
      - elasticsearch
    environment:
      - "SPAN_STORAGE_TYPE=elasticsearch"
      - "ES_SERVER_URLS=http://elasticsearch:9200"
    image: jaegertracing/jaeger-query
    ports:
      - "16686:16686" # /api/* endpoints and Jaeger UI
      - "16687:16687" # admin port: health check at / and metrics at /metrics
    restart: unless-stopped
